#include <HAL.h>
inline void
InitAll (void) {

//InitPort
//  BUTTONS_DDR &= 0 << BUTTON_PLUS | 0 << BUTTON_MINUS;
//  BUTTONS_PORT |= 1 << BUTTON_PLUS | 1 << BUTTON_MINUS;

  INDICATOR_DIGITS_DDR = 0b111;
  INDICATOR_DIGITS_PORT = 0b11000;
  INDICATOR_SEGMENTS_DDR = 0xFF;

}
